version: '3.8'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./target/landmarks.war:/usr/local/tomcat/webapps/landmarks.war
    environment:
      - CATALINA_HOME = /usr/local/tomcat
    depends_on:
      - service-db

  service-db:
    container_name: postgres10_container
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - /var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container1
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - service-db